## Студенческий Активизм и доход

В этом ноутбуке я буду проводить анализ результатов Социологического опроса выпускников в рамках проведения научной работы по изучению влияния студенческого актвиизма в университетские годы на будущий финансовый успех

## 1. EDA

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns

df = pd.read_csv("Sociological_research_form_responces.csv", sep=",")

df.head()

,Timestamp,Укажите ваш пол:,Как давно вы закончили бакалавриат?,Укажите ваш наивысший уровень образования:,Какой университет вы закончили?,Форма обучения на бакалавриате:,Как бы вы оценили материальное положение вашей семьи на момент вашего поступления в университет?,Работали ли вы во время обучения в университете?,Состояли ли вы во время обучения в университете в каких-либо студенческих общественных организациях?,В каких студенческих организациях вы состояли?,...,В каком размере вы получали скидку?,Имели ли вы льготный статус при получении скидки?,Получали ли вы надбавку к базовой стипендии или президентскую стипендию во время обучения?,Ваш текущий трудовой статус:,Сфера вашей текущей профессиональной деятельности:,Связана ли ваша текущая работа с полученной в университете специальностью?,Занимаете ли вы руководящую должность?,Продолжаете ли вы заниматься волонтёрской или общественной деятельностью после окончания университета?,Ваш текущий ежемесячный доход (до вычета налогов) в белорусских рублях:,"Как вы считаете, помогло ли вам участие в студенческих организациях при трудоустройстве?"
0,10/04/2026 13:43:00,Мужской,1-2 года,Бакалавр,ИБ БГУ,Платная,Выше среднего,"Нет, не работал(а)","Нет, не состоял",NaN,...,40%,Нет,NaN,Найм на полную ставку,Финансы,Частично связана,Нет,Нет,3000-5000 BYN,Нет
1,10/04/2026 13:53:50,Женский,1-2 года,Бакалавр,ИБ БГУ,Платная,Выше среднего,"Да, подрабатывал(а) эпизодически","Да, состоял","ПрофКом, БРСМ, Старостат",...,60%,Нет,NaN,Найм на полную ставку,Маркетинг,Частично связана,Нет,Нет,3000-5000 BYN,Нет
2,10/04/2026 14:03:45,Женский,1-2 года,Бакалавр,ИБ БГУ,Платная,Выше среднего,"Нет, не работал(а)","Нет, не состоял",NaN,...,Не получал скидку,Нет,NaN,Безработный,Предпринимательство,Частично связана,"Да, первого звена","Да, эпизодически",Предпочитаю не отвечать,Не участвовал в студенческих организациях
3,10/04/2026 14:05:03,Мужской,3-5 лет,Магистр,ИБ БГУ,Платная,Выше среднего,"Да, работал(а) на полставки","Да, состоял",Студенческий союз,...,60%,Нет,NaN,Найм на полную ставку,IT,"Да, напрямую",Нет,Нет,Более 10000 BYN,"Да, напрямую (упоминал в резюме, нашел через п..."
4,10/04/2026 14:07:01,Женский,1-2 года,Бакалавр,ИБ БГУ,Платная,Среднее,"Нет, не работал(а)","Да, состоял","Студенческий союз, ПрофКом, БРСМ",...,60%,Нет,NaN,Найм на пол ставки,Маркетинг,Частично связана,Нет,"Да, эпизодически",до 1500 BYN,"Да, напрямую (упоминал в резюме, нашел через п..."

In [8]:
df.isnull().sum()

Timestamp                                                                                                      0
Укажите ваш пол:                                                                                               0
Как давно вы закончили бакалавриат?                                                                            0
Укажите ваш наивысший уровень образования:                                                                     0
Какой университет вы закончили?                                                                                0
Форма обучения на бакалавриате:                                                                                0
Как бы вы оценили материальное положение вашей семьи на момент вашего поступления в университет?               0
Работали ли вы во время обучения в университете?                                                               0
Состояли ли вы во время обучения в университете в каких-либо студенческих общественных организациях?           0
  В каких студенческих организациях вы состояли?                                                              10
Сколько времени в общем у вас уходило на вовлеченность во все студенческие организации в неделю (в часах)?    11
Сколько лет вы состояли в студенческом союзе?                                                                 10
Какие навыки, по вашему мнению, вы приобрели благодаря участию в студенческих организациях?                   10
Кто в основном оплачивал вашу учёбу?                                                                           8
Получали ли вы скидку во время обучения?                                                                       8
В каком размере вы получали скидку?                                                                            8
Имели ли вы льготный статус при получении скидки?                                                              8
Получали ли вы надбавку к базовой стипендии или президентскую стипендию во время обучения?                    22
Ваш текущий трудовой статус:                                                                                   0
Сфера вашей текущей профессиональной деятельности:                                                             0
Связана ли ваша текущая работа с полученной в университете специальностью?                                     0
Занимаете ли вы руководящую должность?                                                                         0
Продолжаете ли вы заниматься волонтёрской или общественной деятельностью после окончания университета?         0
Ваш текущий ежемесячный доход (до вычета налогов) в белорусских рублях:                                        0
Как вы считаете, помогло ли вам участие в студенческих организациях при трудоустройстве?                       0
dtype: int64

In [15]:
# Обработка пропусков
df['Сколько_часов_в_неделю?'] = df['Сколько_часов_в_неделю?'].fillna(0)
df['Сколько_лет_в_СС?'] = df['Сколько_лет_в_СС?'].fillna('Не состоял')
df.iloc[:, 9] = df.iloc[:, 9].fillna('Не состоял ни в одной')  # организации
df.iloc[:, 12] = df.iloc[:, 12].fillna('Не участвовал')  # навыки

df['Скидка'] = df['Скидка'].fillna('Не применимо')
df['Льготник'] = df['Льготник'].fillna('Не применимо')
df.iloc[:, 15] = df.iloc[:, 15].fillna('Не применимо')  # размер скидки
df['Надбавка к стипендии'] = df['Надбавка к стипендии'].fillna('Не применимо')

#Делаю имена колонок короче для удобства
col = {
    df.columns[1]: 'пол',
    df.columns[6]: 'мат_положение',
    df.columns[7]: 'работа_во_время',
    df.columns[8]: 'Состоял_в_Студ._Организациях?',
    df.columns[10]: 'Сколько_часов_в_неделю?',
    df.columns[11]: 'Сколько_лет_в_СС?',
    df.columns[14]: 'Скидка',
    df.columns[18]: 'Трудовой_статус',
    df.columns[21]: 'Руководитель?',
    df.columns[23]: 'Доход',
    df.columns[5]: 'Форма_обучения',
    df.columns[3]: 'образование',
    df.columns[16]: 'Льготник',
    df.columns[17]: 'Надбавка к стипендии',
}
df = df.rename(columns=col)



income_map = {
    'до 1500 BYN': 1000,
    '1500-2000 BYN': 1750,
    '2000-3000 BYN': 2500,
    '3000-5000 BYN': 4000,
    '5000-7500 BYN': 6250,
    '7500-10000 BYN': 8750,
    'Более 10000 BYN': 13000,  # консервативная оценка, но все же
}
df['Доход_числ'] = df['Доход'].map(income_map)

# Формула активизма
df['Активист'] = (
    (df['Сколько_лет_в_СС?'] != 'Не состоял') |
    ((df['Скидка'].isin(['Да, 1 год', 'Да, 2 года', 'Да, 3 года'])) & (df['Льготник'] == 'Нет')) |
    (df['Надбавка к стипендии'].isin(['Да, 1 год', 'Да, 2 года', 'Да, 3 года']))
).astype(int)

df['Сколько_часов_в_неделю?'] = pd.to_numeric(df['Сколько_часов_в_неделю?'], errors='coerce')

wealth_map = {'Ниже среднего': 1, 'Среднее': 2, 'Выше среднего': 3}
df['мат_полож_числ'] = df['мат_положение'].map(wealth_map)

with pd.option_context('display.max_columns', None):
    display(df.head())

,Timestamp,пол,Как давно вы закончили бакалавриат?,образование,Какой университет вы закончили?,Форма_обучения,мат_положение,работа_во_время,Состоял_в_Студ._Организациях?,В каких студенческих организациях вы состояли?,Сколько_часов_в_неделю?,Сколько_лет_в_СС?,"Какие навыки, по вашему мнению, вы приобрели благодаря участию в студенческих организациях?",Кто в основном оплачивал вашу учёбу?,Скидка,В каком размере вы получали скидку?,Льготник,Надбавка к стипендии,Трудовой_статус,Сфера вашей текущей профессиональной деятельности:,Связана ли ваша текущая работа с полученной в университете специальностью?,Руководитель?,Продолжаете ли вы заниматься волонтёрской или общественной деятельностью после окончания университета?,Доход,"Как вы считаете, помогло ли вам участие в студенческих организациях при трудоустройстве?",Доход_числ,Активист,мат_полож_числ
0,10/04/2026 13:43:00,Мужской,1-2 года,Бакалавр,ИБ БГУ,Платная,Выше среднего,"Нет, не работал(а)","Нет, не состоял",Не состоял ни в одной,0.0,Не состоял,Не участвовал,Семья,"Да, 1 год",40%,Нет,Не применимо,Найм на полную ставку,Финансы,Частично связана,Нет,Нет,3000-5000 BYN,Нет,4000.0,1,3
1,10/04/2026 13:53:50,Женский,1-2 года,Бакалавр,ИБ БГУ,Платная,Выше среднего,"Да, подрабатывал(а) эпизодически","Да, состоял","ПрофКом, БРСМ, Старостат",1.0,Не состоял,"Лидерство, Организация и управление, Командная...",Семья,"Да, 2 года",60%,Нет,Не применимо,Найм на полную ставку,Маркетинг,Частично связана,Нет,Нет,3000-5000 BYN,Нет,4000.0,1,3
2,10/04/2026 14:03:45,Женский,1-2 года,Бакалавр,ИБ БГУ,Платная,Выше среднего,"Нет, не работал(а)","Нет, не состоял",Не состоял ни в одной,0.0,Не состоял,Не участвовал,Семья,Нет,Не получал скидку,Нет,Не применимо,Безработный,Предпринимательство,Частично связана,"Да, первого звена","Да, эпизодически",Предпочитаю не отвечать,Не участвовал в студенческих организациях,NaN,0,3
3,10/04/2026 14:05:03,Мужской,3-5 лет,Магистр,ИБ БГУ,Платная,Выше среднего,"Да, работал(а) на полставки","Да, состоял",Студенческий союз,20.0,3 года,"Тайм-менеджмент, Лидерство, Организация и упра...",Семья,"Да, 3 года",60%,Нет,Не применимо,Найм на полную ставку,IT,"Да, напрямую",Нет,Нет,Более 10000 BYN,"Да, напрямую (упоминал в резюме, нашел через п...",13000.0,1,3
4,10/04/2026 14:07:01,Женский,1-2 года,Бакалавр,ИБ БГУ,Платная,Среднее,"Нет, не работал(а)","Да, состоял","Студенческий союз, ПрофКом, БРСМ",25.0,3 года,"Тайм-менеджмент, Организация и управление, Ком...",Семья,"Да, 3 года",60%,Нет,Не применимо,Найм на пол ставки,Маркетинг,Частично связана,Нет,"Да, эпизодически",до 1500 BYN,"Да, напрямую (упоминал в резюме, нашел через п...",1000.0,1,2

На этом этапе работы с данными я обработал все пропуски, упростил наиболее частовызываемые колонки для простоты обращения, перевел часы участия в студорганизациях в нумерические значения, а также создал несколько новых колонок - Активист (да/нет, основываясь на моец формуле), нумерическое мат_положение, а также числовой доход (взато по середине промежутка)

## 2. Описательная статистика

In [16]:
print("=== Часы в неделю (только активисты) ===")
print(df.loc[df['Активист']==1, 'Сколько_часов_в_неделю?'].describe())

print("\n=== Доход (midpoint) ===")
print(df['Доход_числ'].describe())

print("\n=== Доход: модальная категория ===")
print(df['Доход'].value_counts())

=== Часы в неделю (только активисты) ===
count    22.000000
mean      7.363636
std       8.807710
min       0.000000
25%       0.000000
50%       4.500000
75%      10.000000
max      25.000000
Name: Сколько_часов_в_неделю?, dtype: float64

=== Доход (midpoint) ===
count       26.000000
mean      4221.153846
std       3370.702392
min       1000.000000
25%       1937.500000
50%       2500.000000
75%       5687.500000
max      13000.000000
Name: Доход_числ, dtype: float64

=== Доход: модальная категория ===
Доход
2000-3000 BYN              7
3000-5000 BYN              5
Предпочитаю не отвечать    4
1500-2000 BYN              4
до 1500 BYN                3
5000-7500 BYN              3
Более 10000 BYN            2
7500-10000 BYN             2
Name: count, dtype: int64

In [21]:
desc_cols = ['пол', 'Как давно вы закончили бакалавриат?', 'образование', 'Форма_обучения', 
             'мат_положение', 'работа_во_время', 'Состоял_в_Студ._Организациях?', 'Доход']
for c in desc_cols:
    print(f"\n=== {c} ===")
    vc = df[c].value_counts()
    pct = (vc / len(df) * 100).round(1)
    print(pd.DataFrame({'n': vc, '%': pct}))

=== пол ===
          n     %
пол
Женский  19  63.3
Мужской  11  36.7

=== Как давно вы закончили бакалавриат? ===
                                      n     %
Как давно вы закончили бакалавриат?
1-2 года                             18  60.0
3-5 лет                               5  16.7
> 10 лет                              4  13.3
Не закончил                           2   6.7
6-10 лет                              1   3.3

=== образование ===
              n     %
образование
Бакалавр     25  83.3
Магистр       5  16.7

=== Форма_обучения ===
                 n     %
Форма_обучения
Платная         22  73.3
Бюджетная        8  26.7

=== мат_положение ===
                n     %
мат_положение
Среднее        14  46.7
Выше среднего  13  43.3
Ниже среднего   3  10.0

=== работа_во_время ===
                                     n     %
работа_во_время
Нет, не работал(а)                  11  36.7
Да, работал(а) на полставки          9  30.0
Да, подрабатывал(а) эпизодически     8  26.7
Да, работал(а) полный рабочий день   2   6.7

=== Состоял_в_Студ._Организациях? ===
                                n     %
Состоял_в_Студ._Организациях?
Да, состоял                    20  66.7
Нет, не состоял                10  33.3

=== Доход ===
                         n     %
Доход
2000-3000 BYN            7  23.3
3000-5000 BYN            5  16.7
Предпочитаю не отвечать  4  13.3
1500-2000 BYN            4  13.3
до 1500 BYN              3  10.0
5000-7500 BYN            3  10.0
Более 10000 BYN          2   6.7
7500-10000 BYN           2   6.7

## 3. Кросс-табуляция

In [27]:
cross_tabulation_1 = pd.crosstab(df['Состоял_в_Студ._Организациях?'], df['Доход'], margins=True)
display(cross_tabulation_1)

cross_tabulation_1_pct = pd.crosstab(df['Состоял_в_Студ._Организациях?'], df['Доход'], normalize='index') * 100
display(cross_tabulation_1_pct.round(1))

cross_tabulation_2 = pd.crosstab(df['Активист'], df['Доход'], margins=True)
display(cross_tabulation_2)

cross_tabulation_2_pct = pd.crosstab(df['Активист'], df['Доход'], normalize='index') * 100
display(cross_tabulation_2_pct.round(1))

cross_tabulation_3 = pd.crosstab(df['мат_положение'], df['Активист'], margins=True)
display(cross_tabulation_3)

cross_tabulation_3_pct = pd.crosstab(df['мат_положение'], df['Активист'], normalize='index') * 100
display(cross_tabulation_3_pct.round(1))

cross_tabulation_4 = pd.crosstab(df['Сколько_часов_в_неделю?'], df['Доход'], margins=True)
display(cross_tabulation_4)

cross_tabulation_4_pct = pd.crosstab(df['Сколько_часов_в_неделю?'], df['Доход'], normalize='index') * 100
display(cross_tabulation_4_pct.round(1))

cross_tabulation_5 = pd.crosstab(df['работа_во_время'], df['Доход'], margins=True)
display(cross_tabulation_5)

cross_tabulation_5_pct = pd.crosstab(df['работа_во_время'], df['Доход'], normalize='index') * 100
display(cross_tabulation_5_pct.round(1))

cross_tabulation_6 = pd.crosstab(df['Руководитель?'], df['Состоял_в_Студ._Организациях?'], margins=True)
display(cross_tabulation_6)

cross_tabulation_6_pct = pd.crosstab(df['Руководитель?'], df['Состоял_в_Студ._Организациях?'], normalize='index') * 100
display(cross_tabulation_6_pct.round(1))

cross_tabulation_7 = pd.crosstab(df['Руководитель?'], df['Активист'], margins=True)
display(cross_tabulation_7)

cross_tabulation_7_pct = pd.crosstab(df['Руководитель?'], df['Активист'], normalize='index') * 100
display(cross_tabulation_7_pct.round(1))

cross_tabulation_8 = pd.crosstab(df['образование'], df['Доход'], margins=True)
display(cross_tabulation_8)

cross_tabulation_8_pct = pd.crosstab(df['образование'], df['Доход'], normalize='index') * 100
display(cross_tabulation_8_pct.round(1))

cross_tabulation_9 = pd.crosstab(df['пол'], df['Доход'], margins=True)
display(cross_tabulation_9)

cross_tabulation_9_pct = pd.crosstab(df['пол'], df['Доход'], normalize='index') * 100
display(cross_tabulation_9_pct.round(1))

Доход,1500-2000 BYN,2000-3000 BYN,3000-5000 BYN,5000-7500 BYN,7500-10000 BYN,Более 10000 BYN,Предпочитаю не отвечать,до 1500 BYN,All
Состоял_в_Студ._Организациях?,,,,,,,,,
"Да, состоял",3,4,3,2,1,1,3,3,20
"Нет, не состоял",1,3,2,1,1,1,1,0,10
All,4,7,5,3,2,2,4,3,30

Доход,1500-2000 BYN,2000-3000 BYN,3000-5000 BYN,5000-7500 BYN,7500-10000 BYN,Более 10000 BYN,Предпочитаю не отвечать,до 1500 BYN
Состоял_в_Студ._Организациях?,,,,,,,,
"Да, состоял",15.0,20.0,15.0,10.0,5.0,5.0,15.0,15.0
"Нет, не состоял",10.0,30.0,20.0,10.0,10.0,10.0,10.0,0.0

Доход,1500-2000 BYN,2000-3000 BYN,3000-5000 BYN,5000-7500 BYN,7500-10000 BYN,Более 10000 BYN,Предпочитаю не отвечать,до 1500 BYN,All
Активист,,,,,,,,,
0,1,2,1,1,0,1,1,1,8
1,3,5,4,2,2,1,3,2,22
All,4,7,5,3,2,2,4,3,30

Доход,1500-2000 BYN,2000-3000 BYN,3000-5000 BYN,5000-7500 BYN,7500-10000 BYN,Более 10000 BYN,Предпочитаю не отвечать,до 1500 BYN
Активист,,,,,,,,
0,12.5,25.0,12.5,12.5,0.0,12.5,12.5,12.5
1,13.6,22.7,18.2,9.1,9.1,4.5,13.6,9.1

Активист       0   1  All
мат_положение
Выше среднего  3  10   13
Ниже среднего  1   2    3
Среднее        4  10   14
All            8  22   30

Активист          0     1
мат_положение
Выше среднего  23.1  76.9
Ниже среднего  33.3  66.7
Среднее        28.6  71.4

Доход,1500-2000 BYN,2000-3000 BYN,3000-5000 BYN,5000-7500 BYN,7500-10000 BYN,Более 10000 BYN,Предпочитаю не отвечать,до 1500 BYN,All
Сколько_часов_в_неделю?,,,,,,,,,
0.0,2,4,2,1,1,1,3,0,14
1.0,0,0,2,0,0,0,0,0,2
2.0,0,1,0,0,0,0,0,0,1
3.0,0,0,0,0,0,0,0,1,1
4.0,0,1,0,0,0,0,0,0,1
5.0,0,0,0,1,0,0,0,1,2
6.0,0,0,0,0,1,0,0,0,1
8.0,1,0,0,0,0,0,0,0,1
10.0,1,1,0,0,0,0,0,0,2
20.0,0,0,0,1,0,1,1,0,3
25.0,0,0,1,0,0,0,0,1,2
All,4,7,5,3,2,2,4,3,30

Доход,1500-2000 BYN,2000-3000 BYN,3000-5000 BYN,5000-7500 BYN,7500-10000 BYN,Более 10000 BYN,Предпочитаю не отвечать,до 1500 BYN
Сколько_часов_в_неделю?,,,,,,,,
0.0,14.3,28.6,14.3,7.1,7.1,7.1,21.4,0.0
1.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0
2.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0
3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0
4.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0
5.0,0.0,0.0,0.0,50.0,0.0,0.0,0.0,50.0
6.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0
8.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10.0,50.0,50.0,0.0,0.0,0.0,0.0,0.0,0.0
20.0,0.0,0.0,0.0,33.3,0.0,33.3,33.3,0.0
25.0,0.0,0.0,50.0,0.0,0.0,0.0,0.0,50.0

Доход,1500-2000 BYN,2000-3000 BYN,3000-5000 BYN,5000-7500 BYN,7500-10000 BYN,Более 10000 BYN,Предпочитаю не отвечать,до 1500 BYN,All
работа_во_время,,,,,,,,,
"Да, подрабатывал(а) эпизодически",1,3,2,0,1,0,1,0,8
"Да, работал(а) на полставки",1,0,1,1,1,2,2,1,9
"Да, работал(а) полный рабочий день",0,0,1,1,0,0,0,0,2
"Нет, не работал(а)",2,4,1,1,0,0,1,2,11
All,4,7,5,3,2,2,4,3,30

Доход,1500-2000 BYN,2000-3000 BYN,3000-5000 BYN,5000-7500 BYN,7500-10000 BYN,Более 10000 BYN,Предпочитаю не отвечать,до 1500 BYN
работа_во_время,,,,,,,,
"Да, подрабатывал(а) эпизодически",12.5,37.5,25.0,0.0,12.5,0.0,12.5,0.0
"Да, работал(а) на полставки",11.1,0.0,11.1,11.1,11.1,22.2,22.2,11.1
"Да, работал(а) полный рабочий день",0.0,0.0,50.0,50.0,0.0,0.0,0.0,0.0
"Нет, не работал(а)",18.2,36.4,9.1,9.1,0.0,0.0,9.1,18.2

Состоял_в_Студ._Организациях?  Да, состоял  Нет, не состоял  All
Руководитель?
Да, высшего звена                        1                1    2
Да, первого звена                        2                2    4
Да, среднего звена                       3                2    5
Нет                                     14                5   19
All                                     20               10   30

Состоял_в_Студ._Организациях?  Да, состоял  Нет, не состоял
Руководитель?
Да, высшего звена                     50.0             50.0
Да, первого звена                     50.0             50.0
Да, среднего звена                    60.0             40.0
Нет                                   73.7             26.3

Активист            0   1  All
Руководитель?
Да, высшего звена   1   1    2
Да, первого звена   1   3    4
Да, среднего звена  1   4    5
Нет                 5  14   19
All                 8  22   30

Активист               0     1
Руководитель?
Да, высшего звена   50.0  50.0
Да, первого звена   25.0  75.0
Да, среднего звена  20.0  80.0
Нет                 26.3  73.7

Доход,1500-2000 BYN,2000-3000 BYN,3000-5000 BYN,5000-7500 BYN,7500-10000 BYN,Более 10000 BYN,Предпочитаю не отвечать,до 1500 BYN,All
образование,,,,,,,,,
Бакалавр,4,6,5,3,2,0,3,2,25
Магистр,0,1,0,0,0,2,1,1,5
All,4,7,5,3,2,2,4,3,30

Доход,1500-2000 BYN,2000-3000 BYN,3000-5000 BYN,5000-7500 BYN,7500-10000 BYN,Более 10000 BYN,Предпочитаю не отвечать,до 1500 BYN
образование,,,,,,,,
Бакалавр,16.0,24.0,20.0,12.0,8.0,0.0,12.0,8.0
Магистр,0.0,20.0,0.0,0.0,0.0,40.0,20.0,20.0

Доход,1500-2000 BYN,2000-3000 BYN,3000-5000 BYN,5000-7500 BYN,7500-10000 BYN,Более 10000 BYN,Предпочитаю не отвечать,до 1500 BYN,All
пол,,,,,,,,,
Женский,3,3,4,1,2,0,3,3,19
Мужской,1,4,1,2,0,2,1,0,11
All,4,7,5,3,2,2,4,3,30

Доход,1500-2000 BYN,2000-3000 BYN,3000-5000 BYN,5000-7500 BYN,7500-10000 BYN,Более 10000 BYN,Предпочитаю не отвечать,до 1500 BYN
пол,,,,,,,,
Женский,15.8,15.8,21.1,5.3,10.5,0.0,15.8,15.8
Мужской,9.1,36.4,9.1,18.2,0.0,18.2,9.1,0.0

## 4. Корреляционный анализ

In [22]:
from scipy.stats import chi2_contingency, spearmanr, pointbiserialr

def cramers_v(var1, var2):
    ct = pd.crosstab(var1, var2)
    chi2, p, dof, expected = chi2_contingency(ct)
    n = ct.sum().sum()
    min_dim = min(ct.shape) - 1
    v = np.sqrt(chi2 / (n * min_dim)) if min_dim > 0 else 0
    return v, p

v, p = cramers_v(df['Состоял_в_Студ._Организациях?'], df['Доход'])
print(f"Cramér's V = {v:.3f}, p = {p:.3f}")



rho, p = spearmanr(df['мат_полож_числ'], df['Доход_числ'], nan_policy='omit')
print(f"Spearman rho = {rho:.3f}, p = {p:.3f}")


mask = df['Доход_числ'].notna()
r, p = pointbiserialr(df.loc[mask, 'Активист'], df.loc[mask, 'Доход_числ'])
print(f"Point-biserial r = {r:.3f}, p = {p:.3f}")

Cramér's V = 0.296, p = 0.917
Spearman rho = 0.210, p = 0.303
Point-biserial r = -0.038, p = 0.853

## 5. Тест Манна-Уитни

In [19]:
from scipy.stats import mannwhitneyu

mask = df['Доход_числ'].notna()
activists = df.loc[mask & (df['Активист']==1), 'Доход_числ']
non_activists = df.loc[mask & (df['Активист']==0), 'Доход_числ']

stat, p = mannwhitneyu(activists, non_activists, alternative='two-sided')
print(f"Mann-Whitney U = {stat:.1f}, p = {p:.3f}")
print(f"Activists median: {activists.median()}, Non-activists median: {non_activists.median()}")

Mann-Whitney U = 68.0, p = 0.953
Activists median: 2500.0, Non-activists median: 2500.0

In [ ]:
n1, n2 = len(activists), len(non_activists)
r_rb = 1 - (2 * stat) / (n1 * n2)
print(f"Rank-biserial r = {r_rb:.3f}")

Rank-biserial r = -0.023

## 6. Фишер

In [25]:
from scipy.stats import fisher_exact
# For 2x2 tables (e.g., activism × leadership yes/no)
ct = pd.crosstab(df['Активист'], df['Руководитель?'] != 'Нет')
odds_ratio, p = fisher_exact(ct)
print(f"OR = {odds_ratio:.2f}, p = {p:.3f}")

OR = 0.95, p = 1.000

In [26]:
# Among activists: does family wealth predict income?
act_df = df[df['Активист']==1 & df['Доход_числ'].notna()]
print(act_df.groupby('мат_положение')['Доход_числ'].median())

# Among non-activists: same
nact_df = df[(df['Активист']==0) & df['Доход_числ'].notna()]
print(nact_df.groupby('мат_положение')['Доход_числ'].median())

мат_положение
Выше среднего    4000.0
Ниже среднего    1750.0
Среднее          2500.0
Name: Доход_числ, dtype: float64
мат_положение
Выше среднего     4375.0
Ниже среднего    13000.0
Среднее           2125.0
Name: Доход_числ, dtype: float64

## 7. Подгрупповой анализ: парадокс Симпсона и когортные эффекты

In [39]:
mask = df['Доход_числ'].notna()

print("=== Медианный доход по когортам выпуска × активизм ===\n")
cohort_table = df[mask].groupby(
    ['Как давно вы закончили бакалавриат?', 'Активист']
)['Доход_числ'].agg(['median', 'mean', 'count'])
display(cohort_table)

=== Медианный доход по когортам выпуска × активизм ===

                                              median         mean  count
Как давно вы закончили бакалавриат? Активист
1-2 года                            0         1375.0  1375.000000      2
                                    1         2500.0  3615.384615     13
3-5 лет                             0         2500.0  3750.000000      3
                                    1         7750.0  7750.000000      2
6-10 лет                            1         8750.0  8750.000000      1
> 10 лет                            0         8500.0  8500.000000      2
                                    1         4000.0  4000.000000      1
Не закончил                         1         1750.0  1750.000000      2

ВЫВОД: Парадокс Симпсона — внутри каждой когорты активисты зарабатывают 
больше или столько же, но в общей выборке медианы равны. Причина: 
неактивисты непропорционально представлены в старших когортах (3+ лет), 
которые зарабатывают больше просто за счёт стажа.

## 8. Субъективная оценка полезности активизма и доход

In [35]:
# Ключевой вопрос: «Помогло ли участие в студенческих организациях при трудоустройстве?»
help_col = 'Как вы считаете, помогло ли вам участие в студенческих организациях при трудоустройстве? '

print(help_col)


# Бинарная переменная: помогло (напрямую + косвенно) vs остальные
df['Помогло'] = df[help_col].isin([
    'Да, напрямую (упоминал в резюме, нашел через полученные в студенческой организации связи)',
    'Да, косвенно (навыки)'
]).astype(int)

helped = df[mask & (df['Помогло']==1)]['Доход_числ']
not_helped = df[mask & (df['Помогло']==0)]['Доход_числ']

print(f"\n=== Помогло (да) vs Остальные ===")
print(f"Помогло: median={helped.median():.0f}, mean={helped.mean():.0f}, n={len(helped)}")
print(f"Остальные: median={not_helped.median():.0f}, mean={not_helped.mean():.0f}, n={len(not_helped)}")

stat, p = mannwhitneyu(helped, not_helped, alternative='two-sided')
r_rb = 1 - (2 * stat) / (len(helped) * len(not_helped))
print(f"Mann-Whitney U={stat:.1f}, p={p:.3f}, rank-biserial r={r_rb:.3f}")

# Fisher's exact: помогло × доход выше медианы
df['Высокий_доход'] = (df['Доход_числ'] > df.loc[mask, 'Доход_числ'].median()).astype(int)
ct = pd.crosstab(df.loc[mask, 'Помогло'], df.loc[mask, 'Высокий_доход'])
display(ct)

odds, p_fisher = fisher_exact(ct)
print(f"Fisher's exact: OR={odds:.2f}, p={p_fisher:.3f}")

Как вы считаете, помогло ли вам участие в студенческих организациях при трудоустройстве?

=== Помогло (да) vs Остальные ===
Помогло: median=4000, mean=4636, n=11
Остальные: median=2500, mean=3917, n=15
Mann-Whitney U=90.5, p=0.692, rank-biserial r=-0.097

Высокий_доход  0  1
Помогло
0              9  6
1              5  6

Fisher's exact: OR=1.80, p=0.692

In [36]:
# Детализация: напрямую vs косвенно vs нет (среди активистов)
activists_mask = mask & (df['Состоял_в_Студ._Организациях?'] == 'Да, состоял')

print("=== Среди участников организаций: доход по оценке полезности ===\n")
for val in ['Да, напрямую (упоминал в резюме, нашел через полученные в студенческой организации связи)',
            'Да, косвенно (навыки)', 'Нет']:
    sub = df[activists_mask & (df[help_col] == val)]['Доход_числ']
    if len(sub) > 0:
        label = val[:30] + '...' if len(val) > 30 else val
        print(f"  {label}: median={sub.median():.0f}, mean={sub.mean():.0f}, n={len(sub)}")

=== Среди участников организаций: доход по оценке полезности ===

  Да, напрямую (упоминал в резюм...: median=4000, mean=6000, n=3
  Да, косвенно (навыки): median=3250, mean=4125, n=8
  Нет: median=2500, mean=2350, n=5